### ISSUE TITLE
手机端自适应与文章索引问题

### ISSUE THREAD

**Issue by MoeKlng** [HelipengTony/tony#11]
专门注册账号来提建议
1.在手机端无法显示搜索栏，和文章索引。
2.文章索引在极长文章下的滚动或许会很不友好，希望字数达到一定程度可以直接跳转。
（emmmm 由于各种原因，其实我暂时没有用这个主题……或许没有这个问题）

**Comment by HelipengTony** [comment]
感谢反馈！
下一个版本更改 🤣
