### ISSUE TITLE
如何使用友链功能？

### ISSUE THREAD

**Issue by tangdongsheng94** [HelipengTony/tony#14]
hello，作者大大你好，
我昨天下载了你的主题，在使用的时候发现友链功能一直添加不上去。是有个友链分类，然后在文章中写文章将文章所属分类设置为友链的分类，然后在文章下面输入友链的地址，再到设置中设置友链的分类为刚刚创建的分类么？
辛苦作者大大在闲暇的时候能够给与回复，不胜感激

**Comment by HelipengTony** [comment]
是这样操作的😀
