### ISSUE TITLE
【Bug】博客页面模板上的一点小问题

### ISSUE THREAD

**Issue by cattomgithub** [HelipengTony/tony#32]
**描述错误情况**
在博客页面中，页面标题上的“博客页面”按钮并非链接的我自己页面，而是链接了您的博客（https://www.ouorz.com/）。
希望在下一个版本可以解决。
**场景图片**
![QQ截图20190807194351](https://user-images.githubusercontent.com/16714790/62620382-c462b600-b94b-11e9-991f-7d095b5970dd.png)
**版本号**
v4.36

**Comment by HelipengTony** [comment]
已经解决了这个问题了！参见这个 PR #31
