### ISSUE TITLE
希望支持新版wordpress编辑器的画廊功能

### ISSUE THREAD

**Issue by zhrq95** [HelipengTony/tony#39]
用新版wordpress古腾堡编辑器，添加一个三列的画廊，可以将三张图片并排显示在一列（自动裁剪尺寸大的图片），预览时正常。
但是浏览时就变成了三张图片分三行显示，这样每张图片都特别大

**Comment by zhrq95** [comment]
[https://i.loli.net/2019/08/18/yAa8BsXOGYpkCj7.png](url)
[https://i.loli.net/2019/08/18/y4gB51XSkFYIqRP.png](url)

**Comment by zhrq95** [comment]
上图是预览时，下图是浏览时
https://i.loli.net/2019/08/18/yAa8BsXOGYpkCj7.png
https://i.loli.net/2019/08/18/y4gB51XSkFYIqRP.png

**Comment by HelipengTony** [comment]
感谢反馈，目前主题还没适配新编辑器，下个版本更新！

**Comment by zhrq95** [comment]
十分期待hhh
