### ISSUE TITLE
首页全文速览在后台设置评论关闭的情况下依然展示

### ISSUE THREAD

**Issue by cccRaim** [HelipengTony/tony#41]
**描述错误情况**
首页全文速览在后台设置评论关闭的情况下依然展示
**场景图片**
![image](https://user-images.githubusercontent.com/7681138/65665285-c4d71d80-e06d-11e9-9d70-3170377f37db.png)

**版本号**
In the theme style.css, the first couple of lines of codes tell you the version you are at.
4.36
**Additional context**
提交后，评论请求返回为『评论已关闭』，所以实际上就是已经关闭评论了的，所以就没必要展示了。
目前我是在主题编辑器里直接注释掉了评论的展示，但是依然希望有更合理的条件判断

**Comment by HelipengTony** [comment]
感谢反馈，下个版本修正！
