### ISSUE TITLE
关于主题部分页面功能实现的求助

### ISSUE THREAD

**Issue by zatime** [HelipengTony/tony#42]
**功能描述**

1/您的“伙伴”页面中的友链是如何设置的？

2/您的文章内页（https://www.ouorz.com/533）中的《Pokers | 全面高效的教育类沟通协作平台》文章链接是怎么实现的？

3/首页文章列表页左上（研究学习 | TONY）这个部分是如何设置实现的？

4/“终于去了趟 ChinaJoy 2019，BTOC 每个展位都看了一遍，但停的最久的还是 Ubisoft”这种状态的文章类型是如何实现的？我找了很久，都没有找到文章类型这个选项。

上述几个问题，摸索了很久，找不到操作方法，谢谢。

**Comment by HelipengTony** [comment]
后台 => 外观 => 主题设置 可以设置友情链接分类，目前友情链接的添加方式是添加带链接字段的文章，链接字段的输入在编辑文章底部有输入框(需要使用经典编辑器)

内页文章链接也需要使用经典编辑器，在添加媒体按钮右侧有插入文章按钮

文章列表蓝色分类显示风格可在主题设置中设置一个分类的文章显示该风格

状态类型文章暂未支持，我独享的moment😂

感谢反馈，下个版本会增加提示

**Comment by zatime** [comment]
非常感谢，问题都已经解决了。
顺带提点下一个版本的建议：

1. 是否可以调整增加字间距和行间距，默认字间距和行间距阅读起来有点拥挤。
2. 自适应移动端后，文章字体较小，是否可以增加移动端自适应后的字体大小？

期待你的下一个版本。
加油！
