### ISSUE TITLE
手机端主题显示错位

### ISSUE THREAD

**Issue by xzyone** [HelipengTony/tony#44]
手机端主题有两处显示错误（最新版，浏览器为手机Chrome）：

1. 首页全文速览错位：

![1](https://i.loli.net/2019/10/17/zFmMJWtlbhZjYUA.jpg)

2. 文章页评论处电子邮箱文本框显示错误：

![2](https://i.loli.net/2019/10/17/TeKw2Rrmsx5HGbi.jpg)

**Comment by HelipengTony** [comment]
感谢反馈，下个版本修正
