### ISSUE TITLE
关闭评论时文章阅读进度显示不正常

### ISSUE THREAD

**Issue by xzyone** [HelipengTony/tony#45]
当关闭文章评论时，文章阅读进度不能正常显示，文章滚动到最后时，阅读进度条没有到头。

**Comment by HelipengTony** [comment]
感谢反馈，麻烦提供一下网址！

**Comment by xzyone** [comment]
http://www.topsportsgaming.com/

以文章http://www.topsportsgaming.com/day-1/为例

- 关闭评论时
![1.jpg](https://i.loli.net/2019/10/19/6lpcmbKZFkxGwEe.jpg)

- 开启评论时
![2.jpg](https://i.loli.net/2019/10/19/oh2148kiuVZRn6d.jpg)
