### ISSUE TITLE
手机端主题显示错位

### ISSUE THREAD

**Issue by variableYan** [HelipengTony/tony#46]
**描述错误情况**
手机端主题显示错位，分别为：顶部不显示顶部菜单，文章列表标签错位，评论表单超出浏览器。
场景图片前两张为魅族16s pro，后一张为谷歌浏览器

**场景图片**
![S91019-15272251](https://user-images.githubusercontent.com/34568927/67140320-f79abd00-f28b-11e9-8bf9-8abefbab2e2b.png)
![1571472323(1)](https://user-images.githubusercontent.com/34568927/67140323-fa95ad80-f28b-11e9-918a-3334000496f2.jpg)
![S91019-16043431](https://user-images.githubusercontent.com/34568927/67140324-fcf80780-f28b-11e9-9a25-07078a4beb91.png)

**版本号**
wordpress_theme_tony_v4.37

**Comment by HelipengTony** [comment]
感谢反馈，已经有重复issue了，下个版本修正！
