### ISSUE TITLE
pc端分类标签不能滑动

### ISSUE THREAD

**Issue by 0SGYM0** [HelipengTony/tony#49]
![chrome_IUPkc7vsM4](https://user-images.githubusercontent.com/50899976/68838733-2c1e5f00-06fa-11ea-9b1a-654235919fe7.png)
**描述错误情况**

**场景图片**

**版本号**
In the theme style.css, the first couple of lines of codes tell you the version you are at.

**Additional context**

**Comment by HelipengTony** [comment]
感谢反馈，下个版本修改
