### ISSUE TITLE
博主SEO这块怎么样

### ISSUE THREAD

**Issue by Smith-Cruise** [HelipengTony/tony#53]
看了一眼博主的主题，内容都是动态加载的，这样对SEO肯定不好。请问博主的搜索引擎收录数，流量如何。

**Comment by HelipengTony** [comment]
不好...你可以查一下权重啥的...
SEO 问题是准备用 SSR 解决的，但是目前学业和申请太忙了，之后会加上的！
感谢关注！

**Comment by Smith-Cruise** [comment]
不过wordpress这块感觉SSR也没法做吧，也可能是我不知道。🤣

**Comment by HelipengTony** [comment]
用 nodejs 的话，WordPress 使用的是 Mysql 数据库，就是需要用户后端配置一下
理论上来说 PHP 也是可以做 SSR 的，所以后面会首先尝试
