### ISSUE TITLE
文章详情页无法显示

### ISSUE THREAD

**Issue by HelloValue** [HelipengTony/tony#60]
**描述错误情况**
文章编辑后发布，打开文章链接无法正常查看。

**版本号**
最新版

**详情图片**
<img width="461" alt="Snipaste_2019-12-29_20-38-06" src="https://user-images.githubusercontent.com/33114091/71557024-3e224a00-2a7b-11ea-8b99-e662f79b6b87.png">

**Additional context**
浏览器为Chrome和Edge。切换到其他主题，文章正常浏览。主题内未修改任何配置。简单的HelloWorld文章也无法显示。

**Comment by HelipengTony** [comment]
感谢支持! 请检查是否配置好伪静态[https://www.wpdaxue.com/wordpress-rewriterule.html](https://www.wpdaxue.com/wordpress-rewriterule.html)
如有问题可以加入 QQ 群讨论

**Comment by HelloValue** [comment]
> 感谢支持! 请检查是否配置好伪静态https://www.wpdaxue.com/wordpress-rewriterule.html
> 如有问题可以加入 QQ 群讨论

您好，伪静态已配置的。另外，我切换到其他主题情况下文章都是正常访问的。以下为文章链接：
http://valuemar.com/helloword/

P.S：我昨天用了最新版安装包后出现的这个问题。之前没有发生过。用到的Web服务器为Nginx。不知是否能帮忙排查一下？

**Comment by pjcoding** [comment]
我的也是这个问题

**Comment by HelloValue** [comment]
> 我的也是这个问题

我切换到 V4.37 Released 版本没问题了，没用最新代码。
