### ISSUE TITLE
请问是否不支持markdown的代码块语法

### ISSUE THREAD

**Issue by Lichmaker** [HelipengTony/tony#62]
您好，今天刚下载了您的主题来使用，非常的好看，很喜欢！
但是美中不足的是，因为我以前的博文是使用markdown编写的，在迁移过来的过程中，发现 markdown 里的` ``` ` 代码块语法无法正常显示。 想请问是否不支持该语法，还是说仅仅是我使用上的问题呢？

输入内容：
![image](https://user-images.githubusercontent.com/8957712/71897889-d793df00-3192-11ea-965d-d3e62fb5eca3.png)

展示结果：
![image](https://user-images.githubusercontent.com/8957712/71897904-e1b5dd80-3192-11ea-8289-d67ec57a306b.png)

期待回复，希望作者可以在2020年继续更新 :)

**Comment by Diobrandokill** [comment]
我也遇到了同样的问题，但是看作者自己的网站中代码块显示是正常的，应该是使用问题吧，求解+1
