### ISSUE TITLE
Load time on mobile

### ISSUE THREAD

**Issue by sgorki** [HelipengTony/tony#66]
Hey, I've just installed this theme for my site.
But i don't know why mobile page is taking too long to load. Is there something missing or is it because of my hosting provider?
My site: [Quang Thắng](https://quangthang.men)

**Comment by HelipengTony** [comment]
It's loading normally on my side.
Try using **Chrome Devtool => Network** to find out what's taking you so long to load.

**Comment by sgorki** [comment]
> It's loading normally on my side.
> Try using **Chrome Devtool => Network** to find out what's taking you so long to load.

It load just fine on Windows
