### ISSUE TITLE
希望支持mathjax或katex数学公式

### ISSUE THREAD

**Issue by MatrixCoder-Chen** [HelipengTony/tony#70]
这款主题很符合我的口味，蓝白极简，有点像知乎。但是我平时需要写一些有数学公式的博客，但是由于本主题使用vue，必须要在渲染文章完毕后再渲染数学公式，否则不起作用。希望可以加上这个功能，方便使用。

**Comment by HelipengTony** [comment]
感谢提议，下个版本加入！

**Comment by MatrixCoder-Chen** [comment]
> 感谢提议，下个版本加入�！

请问一下什么时候更新

**Comment by HelipengTony** [comment]
> > 感谢提议，下个版本加入�！
> 
> 请问一下什么时候更新

不清楚呢...主要高三还是挺忙的，嫌慢的话我找时间写个文档你可以参考着自己改下

**Comment by MatrixCoder-Chen** [comment]
👍👍👍


---原始邮件---
发件人: &quot;TonyHe&quot;<notifications@github.com&gt;
发送时间: 2020年2月24日(周一) 上午10:05
收件人: &quot;HelipengTony/tony&quot;<tony@noreply.github.com&gt;;
抄送: &quot;Author&quot;<author@noreply.github.com&gt;;&quot;MatrixCoder-Chen&quot;<a20070110a@qq.com&gt;;
主题: Re: [HelipengTony/tony] 希望支持mathjax或katex数学公式 (#70)


  
感谢提议，下个版本加入 ！
  
请问一下什么时候更新
  
不清&#x695A;呢...主要高三还是挺忙的，嫌慢的话我找时间写个文档你可以参考着自己改下
 
&mdash;

**Comment by MatrixCoder-Chen** [comment]
我还有一个建议，就是vue对seo不大友好，希望可以优化一下


---原始邮件---
发件人: &quot;TonyHe&quot;<notifications@github.com&gt;
发送时间: 2020年2月24日(周一) 上午10:05
收件人: &quot;HelipengTony/tony&quot;<tony@noreply.github.com&gt;;
抄送: &quot;Author&quot;<author@noreply.github.com&gt;;&quot;MatrixCoder-Chen&quot;<a20070110a@qq.com&gt;;
主题: Re: [HelipengTony/tony] 希望支持mathjax或katex数学公式 (#70)


  
感谢提议，下个版本加入 ！
  
请问一下什么时候更新
  
不清&#x695A;呢...主要高三还是挺忙的，嫌慢的话我找时间写个文档你可以参考着自己改下
 
&mdash;
