### ISSUE TITLE
集成markdown插件wp editor.md等

### ISSUE THREAD

**Issue by MatrixCoder-Chen** [HelipengTony/tony#73]
*一用上Vue麻烦就多了，其实前台用Vue到目前为止还不是一个明智的选择（后台用一下还是很爽的）*。之前我提了一个关于支持mathjax、katex的数学公式建议 #70 ，其实......可以集成插件wp editor.md之类的，我简单看了一下wp editor.md的代码，它的内部实际上是在**访问时**将md转换为html，那么可以通过简单地捣鼓一下代码就能集成wp editor.md，而且这个插件自带数学公式，岂不是多舒服，而且这个插件还支持一些其他的功能：如代码风格切换、emoj等，还带了一个好用的编辑器，否则在默认编辑器里写md那是什么感受。*可能我的思路有点问题，也请原谅*

**Comment by HelipengTony** [comment]
Vue.js 就是前端框架呀，后端用不了的...
使用插件你可以自行安装，主题不会集成插件，因为要了解插件的结构方法等才能将插件嵌入到主题里(也没有必要)
MarkDown 插件你直接安装即可，编辑器的选择也是插件的工作。输出为 HTML，保存在数据库也就是 HTML，那在使用 Tony 主题的时候关闭默认的 MarkDown 渲染选项就可以了。

**Comment by HelipengTony** [comment]
啊对了，Tony 主题默认的 MarkDown 渲染依赖是 markdown-it，你如果等不及下一个版本更新，可以自行搜索一些 markdown-it 的数学公式渲染插件来使用

**Comment by MatrixCoder-Chen** [comment]
唔，原谅我的鄙见，现在了解了一下markdown-it这个插件，其实有支持数学公式的，配合一个插件：markdown-it-katex

**Comment by MatrixCoder-Chen** [comment]
em......回复那么快，刚把“前端”改成了“前台”
