### ISSUE TITLE
主题文章“上一篇”与“下一篇”按钮的链接错误

### ISSUE THREAD

**Issue by kesongyuan** [HelipengTony/tony#88]
**描述错误情况**
在使用主题时，由于我的网站经过两次域名迁移，不知为何原因导致“上一篇”与“下一篇”按钮的链接域名仍然使用旧域名
**场景图片**
![pic1](https://user-images.githubusercontent.com/59796940/114716542-ba22cd00-9d66-11eb-8b7b-f36c6f1338f0.PNG)
**版本号**
In the theme style.css, the first couple of lines of codes tell you the version you are at.
V4.382 Release
**Additional context**
nothing

**Comment by HelipengTony** [comment]
Hi,
链接错误非主题问题，链接获取自 WordPress 内置函数 `get_previous_post()` 和 `get_next_post()`，不存在其他逻辑。

请检查 WordPress 站点链接等基础设置是否修改。
另外在迁移站点后可能需要修改 MySQL 数据内的站点配置、文章链接等内容，可参考[此处](https://tool.wpjam.com/change-domain/)生成的SQL 语句进行数据库操作。
