### ISSUE TITLE
标签显示并不完整

### ISSUE THREAD

**Issue by Kucashu** [HelipengTony/tony#9]
**描述错误情况**
RT. 桌面端无法操作，影响部分体验。

**场景图片**
![set2](https://user-images.githubusercontent.com/33132228/54074962-ffe15180-42d3-11e9-8634-d2fb37e2e243.png)

**版本号**
您的博客。

**Additional context**
None.

**Comment by HelipengTony** [comment]
感谢反馈，将在下一个版本进行修正！

**Comment by Kucashu** [comment]
> 感谢反馈，将在下一个版本进行修正！

谢谢！
